# This workflow will auth the gcloud cli via Workload Identity Federation.
#
name: Deploy with GCloud

on:
  push:
    branches:
      - "main"

env:
  # PROJECT_ID: ${{ YOUR_PROJECT_ID }} # TODO: update Google Cloud project id
  # SERVICE: YOUR_SERVICE_NAME # TODO: update Cloud Run service name
  REGION: 'us-west1' #YOUR_SERVICE_REGION # TODO: update Cloud Run service region

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider'
          service_account: ${{ secrets.SA_EMAIL }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Install Terraform
        # You may pin to the exact commit or the version.
        # uses: little-core-labs/install-terraform@1e577535d279f1999a5abf60337ddc3ff225e79d
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          # Version of terraform to download
          version: 1.2.4

      - name: ListPubSub
        run: |
          terraform init
          terraform plan